version: "3.3"
services:
  redis:
    image: redis
    ports:
      - 6378:6379
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'bksingh'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'user_password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3306:3306
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      # Where our data will be persisted
      - my-db:/var/lib/mysql
  vegcarts-service:
    image: vegcarts:v2.1
    depends_on:
      - redis
      - db
    ports:
      - 8001:8080
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2g
# Names our volume
volumes:
  my-db:
